language: ruby
script:
  - bundle exec rake test
  - bin/rubocop --config .rubocop.yml
rvm:
  - 2.4
  - 2.5
env:
  - "BUNDLE_GEMFILE=gemfiles/active_support_5_1.gemfile"
  - "BUNDLE_GEMFILE=gemfiles/active_support_5_2.gemfile"
